<template>
  <component :is="iconComponent" :size="size" :stroke-width="strokeWidth" />
</template>

<script setup lang="ts">
import {
  FileSpreadsheet,
  Save,
  Table2,
  Check,
  X,
  AlertTriangle,
  Info,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Plus,
  Minus,
  Trash2,
  Copy,
  Scissors,
  ClipboardPaste,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Paintbrush,
  Palette,
  Grid3x3,
  Filter,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  Undo2,
  Redo2,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Lock,
  Unlock,
  Printer,
  Share2,
  Heart,
  Search,
  FunctionSquare,
  HelpCircle,
  WrapText,
  DollarSign,
  Percent,
  Calendar,
  Settings,
  Download,
  Upload,
  FileInput,
  MoreHorizontal,
  MoreVertical,
  GripVertical,
  Eye,
  EyeOff,
  Columns,
  Rows,
  Merge,
  Split,
  Type,
} from 'lucide-vue-next'
import type { Component } from 'vue'

interface Props {
  name: string
  size?: number
  strokeWidth?: number
}

const props = withDefaults(defineProps<Props>(), {
  size: 16,
  strokeWidth: 2
})

const iconMap: Record<string, Component> = {
  'file-spreadsheet': FileSpreadsheet,
  'save': Save,
  'table': Table2,
  'check': Check,
  'x': X,
  'alert': AlertTriangle,
  'info': Info,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'plus': Plus,
  'minus': Minus,
  'trash': Trash2,
  'copy': Copy,
  'cut': Scissors,
  'paste': ClipboardPaste,
  'bold': Bold,
  'italic': Italic,
  'underline': Underline,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  'paint': Paintbrush,
  'palette': Palette,
  'grid': Grid3x3,
  'filter': Filter,
  'sort': ArrowUpDown,
  'sort-asc': ArrowUp,
  'sort-desc': ArrowDown,
  'undo': Undo2,
  'redo': Redo2,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'maximize': Maximize,
  'minimize': Minimize,
  'lock': Lock,
  'unlock': Unlock,
  'printer': Printer,
  'share': Share2,
  'heart': Heart,
  'search': Search,
  'function': FunctionSquare,
  'help': HelpCircle,
  'wrap-text': WrapText,
  'dollar': DollarSign,
  'percent': Percent,
  'calendar': Calendar,
  'settings': Settings,
  'download': Download,
  'upload': Upload,
  'file-input': FileInput,
  'more-h': MoreHorizontal,
  'more-v': MoreVertical,
  'grip': GripVertical,
  'eye': Eye,
  'eye-off': EyeOff,
  'columns': Columns,
  'rows': Rows,
  'merge': Merge,
  'split': Split,
  'type': Type,
}

const iconComponent = iconMap[props.name] || Info
</script>
